repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c60c980e561ed3e73101667fe8365c609d19a438  # frozen: v0.15.9
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0397b68f6f88c024f1d2b355a9818779f6336d16  # frozen: 0.11.3
    hooks:
      - id: uv-lock
  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a  # frozen: v2.4.2
    hooks:
      - id: codespell
        args: ['--write-changes']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
