version: 2
build:
  os: ubuntu-24.04
  tools:
    python: '3.11'
  commands:
    - pip install -e .  # install the package itself
    - pip install sphinx sphinx-rtd-theme pallets_sphinx_themes  # install doc dependencies
    - sphinx-build -b dirhtml docs $READTHEDOCS_OUTPUT/html
