User's Guide
------------

This part of the documentation is written text and should give you an idea
how to work with Flask.  It's a series of step-by-step instructions for
web development.

.. toctree::
   :maxdepth: 2

   foreword
   installation
   quickstart
   tutorial/index
   testing
   errorhandling
   config
   shell
   patterns/index
   deploying/index
   becomingbig

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

Additional Notes
----------------

Design notes, legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 2

   design
   license
   upgrading
   changelog
